spring:
  security:
    user:
      name: seba
      password: 1234
  liquibase:
    change-log: classpath:liquibase/liquibase-changelog.yml
    enabled: true

logging:
  level:
    com:
      project:
        hero: DEBUG
    org:
      springframework: ERROR