spring:
  security:
    user:
      name: seba
      password: 1234
  liquibase:
    change-log: classpath:liquibase/liquibase-changelog.yml
    enabled: false
  h2:
    console:
      enabled: true
logging:
  level:
    com:
      project:
        hero: DEBUG
    org:
      springframework: DEBUG